version: '3.8'

services:
  app:
    build: .
    container_name: lawbot_app
    restart: always
    ports:
      - "8001:8000"
    # Читаем переменные прямо из файла .env и внедряем в контейнер
    env_file:
      - .env
    volumes:
      # Важно: пробрасываем базу данных наружу, чтобы она не стерлась при обновлении контейнера
      - ./database.db:/app/database.db
      # Если вдруг решим хранить файлы локально или логи
      - ./logs:/app/logs
      - ./temp_files:/app/temp_files
      - ./.env:/app/.env  # <--- ДОБАВЬ ЭТУ СТРОКУ (проброс файла с паролями)