version: '3.8'

services:
  app:
    build: .
    container_name: lawbot_app
    restart: always
    ports:
      - "8001:8000"  # <--- ВНЕШНИЙ 8001, ВНУТРЕННИЙ 8000
    env_file:
      - .env
    environment:
      - TZ=Asia/Jerusalem
      - DATABASE_URL=sqlite:////data/lawbot.db
    volumes:
      - ./temp_files:/app/temp_files
      - ./lawbot_data:/data
    command: gunicorn -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --timeout 300 main:app